default: &defaults
  listen: localhost:9312
  mem_limit: '512M'
  charset_dictpath: "/usr/local/mmseg3/etc"
  charset_type: "zh_cn.utf-8"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
